services:
  nestapp:
    build:  
      context: .  
      dockerfile: Dockerfile
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    container_name: nestapp
    environment:
      - DATABASE_URL=${DATABASE_URL}
      
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: